### ISSUE TITLE
ValueError: invalid literal for int() with base 10 at int(struct.residueNumber(idx)) 

### ISSUE THREAD

**Issue by rraadd88** [haddocking/prodigy#10]
Hi, I encountered this error after running prodigy on some PDB ids (eg. 1TVD, 4E44, 2PUX).
Seems that some residue numbers are not integers for some reason.

Demo code:
I am using `python3_package` branch. 
```
> prodigy 1TVD.pdb  --selection A B --contact_list --pymol_selection 
[+] Reading structure file: 1TVD.pdb
[!] Structure contains gaps:
        A ASP1 < Fragment 0 > A GLY57
        A GLY58 < Fragment 1 > A PRO116
        B ASP1 < Fragment 2 > B GLY57
        B GLY58 < Fragment 3 > B PRO116

[+] Parsed structure file 1TVD (2 chains, 226 residues)
Traceback (most recent call last):
  File "prodigy", line 11, in <module>
    load_entry_point('prodigy', 'console_scripts', 'prodigy')()
  File "prodigy/prodigy/predict_IC.py", line 311, in main
    prodigy.predict(distance_cutoff=cmd.distance_cutoff, acc_threshold=cmd.acc_threshold)
  File "prodigy/prodigy/predict_IC.py", line 146, in predict
    _, cmplx_sasa = execute_freesasa_api(self.structure)
  File "prodigy/prodigy/lib/freesasa_tools.py", line 185, in execute_freesasa_api
    resid = int(struct.residueNumber(idx))
ValueError: invalid literal for int() with base 10: '57B'
```

I wonder if there is any easy way to get around this error.

**Comment by brianjimenez** [comment]
Problem in `1tvd` parsing comes from residue alternative positions.

**Comment by amjjbonvin** [comment]
So two options: 

1) We automatically remove the alternate positions (e.g. using the pdbtools `pdb_selaltloc`)

2) We return a proper error message asking the user to do it (pointing possibly to pdbtools for this purpose)

**Comment by amjjbonvin** [comment]
Option 3: we read the PDB in a column strict format (as done in Fortran for example). But that means that two side-chains will be considered in such a case to evaluate contacts most likely

**Comment by brianjimenez** [comment]
As the error is not coming from the `prodigy` parser, but from `freesasa`'s, I'm inclined about option 2.

**Comment by amjjbonvin** [comment]
Sounds like a good choice indeed.

And we could open an issue in the freesasa git repo

**Comment by brianjimenez** [comment]
`freesasa` is able to deal with inserted residues (see https://github.com/mittinatten/freesasa/issues/30). It seems problem comes from our `lib/freesasa_tools.py`. Investigating.

**Comment by brianjimenez** [comment]
Problem addressed in 8f212b1

**Comment by brianjimenez** [comment]
Tested with structures pointed by user @rraadd88 (`1TVD`, `4E44`).

**Comment by brianjimenez** [comment]
Please note we have merged `python3_package` into master.
