### ISSUE TITLE
Dataset at http://bmm.crick.ac.uk/~bmmadmin/Affinity not available anymore.

### ISSUE THREAD

**Issue by ozkilim** [haddocking/prodigy#15]
Dear Authors,

Thanks so much for the amazing work. 

I am a PhD student at Eotvos Lorand University looking for the dataset provided in the paper:  Kastritis P. L., Moal I. H., Hwang H., Weng Z., Bates P. A., Bonvin A. M. and Janin J.(2011). A structure-based benchmark for protein-protein binding affinity. 

I wanted to know if its still available and if not, what open-source dataset/s you would suggest with affinity data as well as 3D bound structures?

All the best,
Oz

**Comment by CunliangGeng** [comment]
Hi Oz, they are available at https://wenmr.science.uu.nl/prodigy/dataset

**Comment by ozkilim** [comment]
Thank you very much!
