### ISSUE TITLE
prodigy: error: unrecognized arguments: model.pdb

### ISSUE THREAD

**Issue by esraaelmligy** [haddocking/prodigy#16]
Keeps giving me this error for the pdb file argument and i don't really know why

**Comment by rvhonorato** [comment]
Could you please share what are the arguments you are passing to the command line interface?

**Comment by esraaelmligy** [comment]
I have fixed the issue, it seems that the code does not accept any spaces or "-" in the file name.

**But i have came across another error and i can't seem to fix it, so if you could help, the error is:
" Exception: 
[!] Error when running freesasa: 
[!] Error: Radius array is <= 0 for the residue: THR ,atom:  OT1"**

I think that has to do with the way freesasa itself works, but can't seem to find a solution.

**Comment by esraaelmligy** [comment]
I have fixed the issue, it seems that the code does not accept any spaces
or "-" in the file name.

But i have came across another error and i can't seem to fix it, so if you
could help, the error is:
" Exception:
[!] Error when running freesasa:
[!] Error: Radius array is <= 0 for the residue: THR ,atom: OT1"

I think that has to do with the way freesasa itself works, but can't seem
to find a solution

**Comment by esraaelmligy** [comment]
I have fixed the issue, it seems that the code does not accept any spaces or "-" in the file name.

**But i have came across another error and i can't seem to fix it, so if you could help, the error is:
" Exception:
[!] Error when running freesasa:
[!] Error: Radius array is <= 0 for the residue: THR ,atom: OT1"**

I think that has to do with the way freesasa itself works, but can't seem to find a solution

**Comment by esraaelmligy** [comment]
Error2: " Exception:
[!] Error when running freesasa:
[!] Error: Radius array is <= 0 for the residue: THR ,atom: OT1"

Could you please tell me how to fix it?

**Comment by amjjbonvin** [comment]
Try replacing OT1 and OT2 by the PDB nomenclature: O and OXT

**Comment by rvhonorato** [comment]
@esraaelmligy did the proposed fix address your issue?
