### ISSUE TITLE
Unable to install by pip

### ISSUE THREAD

**Issue by xlminfei** [haddocking/prodigy#22]
When I try to install PRODIGY by pip, it looks like something went wrong

minfei@minfei:~$ pip install prodigy
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement prodigy (from versions: none)
ERROR: No matching distribution found for prodigy

**Comment by rvhonorato** [comment]
Thanks for reporting this; the install steps in the readme were indeed wrong, i've just corrected it, please try again with 

```
git clone https://github.com/haddocking/prodigy && cd prodigy
pip install .
```

and please let us know if it works for you

**Comment by xlminfei** [comment]
It works. Thanks!
