### ISSUE TITLE
Improve `Radius array is <= 0 for the residue: ILE ,atom: CD` error message

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/prodigy#24]
Several users have asked for help relating to this error message `Radius array is <= 0 for the residue: ILE ,atom: CD` 

1. https://ask.bioexcel.eu/t/prodigy-error-radius-array-is-0-for-the-residue-ile-atom-cd/4375
2. https://ask.bioexcel.eu/t/error-radius-array-is-0-for-the-residue-ile-atom-cd/2835
3. https://ask.bioexcel.eu/t/gap-in-protein-chain-and-atom-naming-error/3825
4. https://ask.bioexcel.eu/t/prodigy-fails-to-calculate-binding-energy-of-protein-protein-complex/3420
5. https://ask.bioexcel.eu/t/some-problems-in-doing-prodigy/3187

This message specifically seems related to a input structure containing atoms other than CD - which might be the case for structures generated with a few different modelling software.

We could improve the message to already contain the advice on how to proceed;

```text
[!] Error: Radius array is <= 0 for the residue: ILE ,atom: CD
[!] Error: Make sure the atom names in your PDB file match the cannonical naming and belong to default residues
```

**Comment by amjjbonvin** [comment]
Or simply duplicate the parameters of ILE CD1 to ILE CD - then we can handle it directly (as it seems to occur often)
