### ISSUE TITLE
Result Interpretation 

### ISSUE THREAD

**Issue by PodevynLoris** [haddocking/prodigy#26]
Hello, 
I was wondering how to interpret the results of a complex. 

[+] Parsed structure file 7F62_input_fasta_relaxed_rank_005_alphafold2_multimer_v3_model_1_seed_000 (3 chains, 427 residues)
[+] No. of intermolecular contacts: 55
[+] No. of charged-charged contacts: 3
[+] No. of charged-polar contacts: 8
[+] No. of charged-apolar contacts: 12
[+] No. of polar-polar contacts: 5
[+] No. of apolar-polar contacts: 16
[+] No. of apolar-apolar contacts: 11
[+] Percentage of apolar NIS residues: 35.60
[+] Percentage of charged NIS residues: 19.50
[++] Predicted binding affinity (kcal.mol-1):    -10.7
[++] Predicted dissociation constant (M) at 25.0˚C:  1.3e-08

Is the binding affinity score made up of all the "[+]" scores ?

**Comment by amjjbonvin** [comment]
It is a linear combination of those terms. Check the original paper:

A Vangone and A.M.J.J. Bonvin. [Contacts-based prediction of binding affinity in protein-protein complexes](https://elifesciences.org/content/4/e07454). eLife, 4, e07454 (2015).
