### ISSUE TITLE
Contact_list flag

### ISSUE THREAD

**Issue by PodevynLoris** [haddocking/prodigy#28]
Hello, 

I'm currently running prodigy on a protein complex. 
I don't see any changes in the terminal or in the directory when activating the contact_list flag 

Do you have any idea why? 
_______________________________________________________________________________________________
```
(prodigy) loris@big-gpu:~/dev/prodigy$ prodigy 7f62.pdb --selection H,L A
[+] Reading structure file: /home/loris/loris/ground_thruth/7f62.pdb
[!] Structure contains gaps:
        A PRO330 < Fragment 0 > A LYS444
        A GLY447 < Fragment 1 > A SER530
        H GLU1 < Fragment 2 > H ALA119
        L GLN1 < Fragment 3 > L ARG109
[+] Parsed structure file 7f62 (3 chains, 427 residues)
.....
[++] Predicted binding affinity (kcal.mol-1):    -11.5
[++] Predicted dissociation constant (M) at 25.0˚C:  3.6e-09

(prodigy) loris@big-gpu:~/dev/prodigy$ prodigy ground_thruth/7f62.pdb --selection H,L A **--contact_list**
[+] Reading structure file: /home/loris/loris/ground_thruth/7f62.pdb
[!] Structure contains gaps:
        A PRO330 < Fragment 0 > A LYS444
        A GLY447 < Fragment 1 > A SER530
        H GLU1 < Fragment 2 > H ALA119
        L GLN1 < Fragment 3 > L ARG109
[+] Parsed structure file 7f62 (3 chains, 427 residues)
....
[++] Predicted binding affinity (kcal.mol-1):    -11.5
[++] Predicted dissociation constant (M) at 25.0˚C:  3.6e-09
(prodigy) loris@big-gpu:~/dev/prodigy$ 
```

**Comment by amjjbonvin** [comment]
The only difference should be one additional file containing the list of contacts.

Can you find such a file on disk?

**Comment by JoshuaMeyers** [comment]
I am having the same issue and do not see a file written to the cwd (running the example in the readme from the `examples/` directory

**Comment by amjjbonvin** [comment]
Just installed a fresh version (note that I needed to update the freesasa version to 2.2.1 in the pyproject.toml file) and tested the example:

`prodigy 3BZD.pdb --selection A B —contact_list`

with the `—contact_list` option 3BZD.ic is created that contains the list of contacts.

PS: I installed prodigy using a python3.11 version on my mac.
