### ISSUE TITLE
--acc-threshold range?

### ISSUE THREAD

**Issue by tony-res** [haddocking/prodigy#30]
I believe that the `--acc-threshold` parameter specifies the accessibility threshold for the buried surface area analysis. Is this parameter a percentage? I tried changing the default from 0.05 to 1.25 and it worked, but anything larger failed.

My thought is that the IC contact list might help me with the [TAP](https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabpred/tap) criteria. Would the IC residues be similar to the "CDR vicinity" in the TAP calculations?

**Comment by amjjbonvin** [comment]
This parameter defines the relative surface accessibility, which is a fraction between 0 and 1 (but it can be in principle larger than 1 as the SASA of a residue could be larger in the protein than in the reference tripeptide). A value of 0 would select all residues irrespective of their solvent accessibility.
