### ISSUE TITLE
Prodigy v2.1.4 and v2.1.5 appear as v2.1.3

### ISSUE THREAD

**Issue by nlbrown62** [haddocking/prodigy#31]
Just a minor issue - versions 2.1.4 and 2.1.5 of prodigy are both listed as v2.1.3 when running `prodigy -V` on the command line, and is also listed as v2.1.3 by pip after installation. For pip, can this be fixed by bumping the version number in pyproject.toml on line 4? For the command line, it looks like the version is controlled by line 19 of prodigy/predict_IC.py.

**Comment by rvhonorato** [comment]
oops guess we forgot to update it! It has been patched in #32 and I have re-generated the release with this fix.

Thanks for raising this @nlbrown62 👍🏽

**Comment by nlbrown62** [comment]
No problem, thanks for fixing that!
